# # Generated by Django 4.2.3 on 2023-09-02 14:48
#
# import django.contrib.postgres.fields
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('app', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.AlterField(
#             model_name='docs',
#             name='messages',
#             field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
#         ),
#     ]


from django.db import migrations, models

def convert_jsonb_to_text_array(apps, schema_editor):
    Docs = apps.get_model('app', 'Docs')

    for doc in Docs.objects.all():
        # Convert JSONB to a list of strings
        messages_as_text_array = [str(item) for item in doc.messages]
        doc.messages = messages_as_text_array
        doc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_jsonb_to_text_array),
        migrations.AlterField(
            model_name='docs',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
